### ISSUE TITLE
ACEDrawingToolTypeCustom enum causes crash in demo app

### ISSUE THREAD

**Issue by markkrenek** [acerbetti/ACEDrawingView#50]
ACEDrawingToolTypeCustom was added to the top of the ACEDrawingToolType enum essentially  making it the default value for drawTool. This leads to a crash since customDrawTool has not been specified.

The fix is to either move ACEDrawingToolTypeCustom out of the zero position in the enum or to explicitly default drawTool to ACEDrawingToolTypePen in configure().

**Comment by acerbetti** [comment]
Thank you for reporting this bug, I set the first enum back to pen like it was before
