### ISSUE TITLE
Question about updating image cache

### ISSUE THREAD

**Issue by evgeniy-ryadovoy** [acerbetti/ACEDrawingView#56]
Hi.

Thanks for this amazing project. I have one question. 

We have an image on our canvas. So, all paths should be added to it's context. 
When we move our finger by screen - we see line (new paths added through draw cycles). 
But there is only one place, where image grabs the context info: 

- (void)updateCacheImage:(BOOL)redraw

function. It called only when touches end. 
Why we can see line during drawing (instead blank screen and appearing this curve after finishing touch)?

**Comment by cfive2015** [comment]
Call **[self.currentTool draw]** in the drawRect function.
- (void)drawRect:(CGRect)rect
{
#if PARTIAL_REDRAW
    // TODO: draw only the updated part of the image
    [self drawPath];
#else
    switch (self.drawMode) {
        case ACEDrawingModeOriginalSize:
            [self.image drawAtPoint:CGPointZero];
            break;
            
        case ACEDrawingModeScale:
            [self.image drawInRect:self.bounds];
            break;
    }
    **[self.currentTool draw];** // see here
#endif
}

**Comment by evgeniy-ryadovoy** [comment]
Yep, got it! 
Thanks!
