### ISSUE TITLE
How can I integrate this API with swift file?  

### ISSUE THREAD

**Issue by RichikaAGL** [acerbetti/ACEDrawingView#60]
I had integrate this API in swift, issue comes with delegate call from:

1. ACEDrawingView.m
2. - (void)finishDrawing
3. delegate call, doesnot goe inside "if" condition, 

Definition of delegate given in swift file, but call is not made.

Please help. Consider it as urgent!

**Comment by acerbetti** [comment]
the delegate call is optional, why is it a blocker ?

**Comment by RichikaAGL** [comment]
Hi

When I choose the option to change line color, it enters the action delegates, but lineColor doesnot get changed.

func actionSheet(actionSheet: UIActionSheet, clickedButtonAtIndex buttonIndex: Int)
{
		println_debug("\(buttonIndex)")
		switch (buttonIndex)
		{
		case 1:
			self.drawingView.lineColor = UIColor.blackColor()
			break
			
		case 2:
			self.drawingView.lineColor = UIColor.redColor()
			break
			
		case 3:
			self.drawingView.lineColor = UIColor.greenColor()
			break
			
		case 4:
			self.drawingView.lineColor = UIColor.blueColor()
			break
			
		default:
				break
			
		}
	}

**Comment by RichikaAGL** [comment]
Hi, I was able to solve the issue. Thanks.
