### ISSUE TITLE
ACEDraggableText.bundle not found?

### ISSUE THREAD

**Issue by vinzen** [acerbetti/ACEDrawingView#63]
I update to the last version and here is what I got:

```
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[NSBundle initWithURL:]: nil URL argument'
*** First throw call stack:
(
	0   CoreFoundation                      0x00000001067c834b __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x000000010a1e321e objc_exception_throw + 48
	2   CoreFoundation                      0x0000000106831265 +[NSException raise:format:] + 197
	3   Foundation                          0x0000000109cd6b3d -[NSBundle initWithURL:] + 87
	4   Foundation                          0x0000000109cd6ad3 +[NSBundle bundleWithURL:] + 45
	5   ACEDrawingView                      0x0000000105482f6f -[ACEDrawingView configure] + 703
	6   ACEDrawingView                      0x0000000105482c6a -[ACEDrawingView initWithCoder:] + 138
```

The ACEDrawingView is instantiated from a Storyboard.

Cocoapod: 1.0.1
Xcode: 8.0

**Comment by acerbetti** [comment]
Strange, I'm using pod myself in a similar configuration and I don't see this problem.
Can you please check if the resources in png format are downloaded correctly ?

**Comment by vinzen** [comment]
Yeah they are

![capture d ecran 2016-10-07 a 17 25 20](https://cloud.githubusercontent.com/assets/3071874/19195739/0eb5cfa8-8cb3-11e6-860b-2331339de6b1.png)

**Comment by acerbetti** [comment]
I'm not sure why the bundle is not loaded correctly. I just pushed version 2.0.1 which add a check for nil. You can always set the images for the corner of the draggable text tool programmatically using the properties: draggableTextRotateImage & draggableTextCloseImage
