### ISSUE TITLE
applyDrawToImage not present in cocoapods

### ISSUE THREAD

**Issue by lorenzoPrimi** [acerbetti/ACEDrawingView#70]
`- (UIImage *)applyDrawToImage:(UIImage *)baseImage;`

is not present when integrating this library with cocoapods, maybe the library is not updated to the latest version?

**Comment by Tripwire999** [comment]
I noticed that as well, seems like the cocoapods version isn't updated :(

**Comment by acerbetti** [comment]
Sorry about that. I can update the pod later in the day. In the meantime you can update the podspec to point directly to the github repository
