### ISSUE TITLE
disable drawTool

### ISSUE THREAD

**Issue by hfzwhd** [acerbetti/ACEDrawingView#74]
is there any way we could disable a drawTool or any state that will disabled all drawTool options. thanks!

**Comment by hfzwhd** [comment]
interim solution - bring other uiview to front.

**Comment by acerbetti** [comment]
What do you mean with disable ?

**Comment by hfzwhd** [comment]
hi below is the example. when i tap on stickerButton, i was hoping there is some state that would disable the previous state of view. eg aceDrawingView.drawTool = none

@IBAction func textButtonTapped(_ sender: Any) {
 self.aceDrawingView.drawTool = ACEDrawingToolTypeDraggableText
}

@IBAction func brushButtonTapped(_ sender: Any) {
 self.aceDrawingView.drawTool = ACEDrawingToolTypePen
}

@IBAction func stickerButtonTapped(_ sender: Any) {
 ...
}
