### ISSUE TITLE
Text label(ACEDrawingLabelView) missing after save image

### ISSUE THREAD

**Issue by param0091** [acerbetti/ACEDrawingView#76]
Label(ACEDrawingLabelView) not available when save photo. As code no is available in drawTool to draw label over image. Use latest version of library installed with pods.

**Comment by ZhouRR** [comment]
maybe you need call method 'prepareForSnapshot'

**Comment by cor0na** [comment]
I also had the same problem. Calling 'prepareForSnapshot' method does not fix it. Why can not the DraggableText export as UIImage?

**Comment by ZhouRR** [comment]
[ACEDrawingView toImage];
and in UIView+Image.m
- (UIImage *)toImage
{
    UIGraphicsBeginImageContextWithOptions(self.frame.size, NO, 0.0);
    [self.layer renderInContext:UIGraphicsGetCurrentContext()];
    UIImage *newImage = UIGraphicsGetImageFromCurrentImageContext();
    UIGraphicsEndImageContext();
    
    return newImage;
}

**Comment by cor0na** [comment]
@ZhouRR Thanks for your nice code, perfect! I was able to confirm the UIImage included the DraggableText.

**Comment by acerbetti** [comment]
Thanks for the code. Do you mind to submit a PR ? 
I've been very busy and I can't find much time to maintain this project

**Comment by ZhouRR** [comment]
@cor0na No thanks.
@acerbetti No thanks.
