### ISSUE TITLE
Having the ability to store the drawn paths and load them into the view when app is loaded

### ISSUE THREAD

**Issue by JinkProject** [acerbetti/ACEDrawingView#80]
Hello all,

I am trying to use this library to allow users to write their signatures. I am trying to store the signature and give the user the option of reusing the stored signature. How do I accomplish this? At the moment, I'm storing the `pathArray` and loading it when the app is loaded, but I'm not sure how to populate the view using the individual bezierPaths in the `pathArray`. Any help would be greatly appreciated.

**Comment by JinkProject** [comment]
Please disregard. It appears that there is another question similar to this already.

**Comment by acerbetti** [comment]
cloned #65
